Papers             $HOME/DATA/papers
Projects           $HOME/projects
Reports            $HOME/reports
itDATA             $HOME/DATA/it_Data
DATA               $HOME/DATA/data
fdfor              $HOME/projects/fdfor
fileOrgnizer       $HOME/projects/fileOrganizer
